name: ✨ Feature Request
description: Suggest a new feature or enhancement for NextSaaS
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with NextSaaS's goals as a SaaS starter kit
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: |
        Currently, when I try to..., I have to...
        This is frustrating because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        I would like to see...
        This would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      multiple: true
      options:
        - Authentication
        - Database/Supabase
        - UI Components
        - Organization Management
        - Billing/Payments
        - Documentation
        - Developer Experience
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I can help test the implementation
        - label: I can help document this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any mockups, examples, or additional information