name: Update UI Test Badges

on:
  push:
    paths:
      - 'packages/ui/src/**'
      - 'packages/ui/package.json'
  pull_request:
    paths:
      - 'packages/ui/src/**'
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Generate test report and badges
        working-directory: packages/ui
        run: |
          npm run test:update-badges
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            packages/ui/test-status.json
            packages/ui/TEST_STATUS.md
            packages/ui/COMPONENT_GALLERY.md
      
      - name: Commit badge updates
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update UI test badges [skip ci]"
          git push
      
      - name: Comment PR with test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const testStatus = JSON.parse(fs.readFileSync('packages/ui/test-status.json', 'utf8'));
            const coverage = ((testStatus.summary.passedTests / testStatus.summary.totalTests) * 100).toFixed(1);
            
            const comment = `## 📊 UI Test Results
            
            - **Coverage**: ${coverage}%
            - **Tests**: ${testStatus.summary.passedTests}/${testStatus.summary.totalTests} passing
            - **Components**: ${testStatus.summary.totalComponents} tested
            
            [View detailed report](https://github.com/${{ github.repository }}/blob/${{ github.head_ref }}/packages/ui/TEST_STATUS.md)
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })